### PR TITLE
Transfers: Specify verbosity level

### PR DESCRIPTION
**Pull request by Hwesta**
Add -v and -q paramaters to move the logging level up or down.

### CODE REVIEW

**Comment by sevein** [comment]
Can we have an extra `--log-level=INFO|DEBUG|WARNING|ERROR|CRITICAL`?

**Comment by Hwesta** [comment]
Instead of or in addition to -q/-v? How do you suggest having --log-level interact with -q/-v?

**Comment by sevein** [comment]
If `--log-level` is used, I think it should override whatever is the result of combining `-q` and `-v`.

**Comment by Hwesta** [comment]
Sure, that seems reasonable.

**Comment by Hwesta** [comment]
Updated - how does this look? I'll probably squash the commits before merge.

**Comment by sevein** [comment]
👍

**Pull request merged**
