### PR TITLE
Issue 690 empty sip UUID

### PR DESCRIPTION
**Pull request by ThomasEdvardsen**
A first attempt to fix the issue with missing SIP UUID.

Connects to [issue #690](https://github.com/archivematica/Issues/issues/690)

### CODE REVIEW

**Comment by ThomasEdvardsen** [comment]
Need some help to correct the Travis Build...

Code is tested and working.

**Comment by replaceafill** [comment]
Hello @ThomasEdvardsen. My apologies for taking so long to review this for you.

Not sure if you've see the [Travis failures](https://travis-ci.org/artefactual/automation-tools/jobs/541102753#L291-L308) yet. We have [black](https://black.readthedocs.io/en/stable/) set up for linting in the repository and I think in the first error is expecting a [shorter line](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length) and in the second one is expecting a [trailing comma](https://black.readthedocs.io/en/stable/the_black_code_style.html#trailing-commas). So changing those lines shown in the Travis output should fix the problem.

Out of curiosity: have you been able to reproduce the issue consistently? I mean, the API not sending the SIP UUID for completed transfers. I've been wanting to determine its root cause.

**Comment by ThomasEdvardsen** [comment]
Tnanks @replaceafill. Installed Black, and reformatted now :)
Is there a guide on how to set up the developer environment any place? I am using IntelliJ.

The problem with the API not sending SIP UUID occurs from time to time. 

The root cause is not known for me, but @ross-spencer have [updated the docs about this](https://wiki.archivematica.org/Archivematica_API#Status).

**Comment by ross-spencer** [comment]
Hi @ThomasEdvardsen before I forget, can we ask you to complete this [contributor's agreement](https://wiki.archivematica.org/Contributor_Agreement) as we CR and consider merging these changes? I should have mentioned it sooner! Once complete, just email it back to agreement@artefactual.com.

**Comment by ThomasEdvardsen** [comment]
Its already done :)

Thomas


tor. 6. jun. 2019, 16:13 skrev Ross Spencer <notifications@github.com>:

**Comment by ThomasEdvardsen** [comment]
Thanks @cole, I will have a look into it when I get a chance.

**Comment by scollazo** [comment]
@cole what about merging this as is, and create a new pr for your suggestions? I'm being affected by #112 , and this works in my environment.

**Comment by cole** [comment]
Sure. This PR is an improvement on the current state as is, so I'm ok with merging it as is and deferring any improvements.

**Pull request closed without merging**
