### PR TITLE
transfers: archivesspace_ids.py path fix

### PR DESCRIPTION
**Pull request by hakamine**
In bags, metadata directory is in data directory, refs #9728

### CODE REVIEW

**Comment by Hwesta** [comment]
Do we want this to only work for bags then, but not other types of transfers?  Maybe we could add to the beginning
```python
data_path = transfer_path
if os.path.exists(os.path.join(transfer_path, 'data')):  # Assume this is a bag
    data_path = os.path.join(transfer_path, 'data')
```
and use `data_path` for the places that you modified?

**Comment by hakamine** [comment]
Could it be possible to have a more broad solution that also works for standard transfers? (I wasn't sure about how to do in that case, could there be any script in the existing codebase that I could refer to? )

**Comment by Hwesta** [comment]
I think the solution I proposed will also work for standard transfers.  Most incoming transfers have the format:
```
logs/
metadata/
objects/
```
or just
```
metadata/
<objects in the root directory>
```
Bags have a more specific structure:
```
<misc bag file>
data/
```

Archivematica looks for a `metadata` directory at the root level when it looks for metadata files, and bags are restructured to put the contents of the data directory in the root of the unit. So by writing to a file in the `metadata` directory (or the `data/metadata` directory if it exists for a bag), it should work for both bags and non-bags.

**Comment by hakamine** [comment]
Thank you for the explanation. Fixed as proposed.

**Comment by Hwesta** [comment]
:+1:

**Pull request merged**
