### PR TITLE
transfer.py : fix approval API call bug

### PR DESCRIPTION
**Pull request by timothyryanwalsh**
Trailing slash in approve transfer post was resulting in 404 response.

### CODE REVIEW

**Comment by Hwesta** [comment]
Good catch! This is caused by a bug in declaring URLs in Archivematica, which is fixed by artefactual/archivematica#551 and will be in the upcoming AM 1.6 release. Your change should work with both versions though.

**Comment by timothyryanwalsh** [comment]
Glad it's gotten resolved! If I understand you correctly, this means when we upgrade to 1.6, the trailing slash in "/api/transfer/approve/" should work fine?

**Comment by Hwesta** [comment]
Correct, once you upgrade to AM 1.6 "/api/transfer/approve/" should work.

**Comment by Hwesta** [comment]
This bug is fixed in AM 1.6, and the fix was backported to stable/1.5.x where it was introduced.  I don't think this PR is needed anymore, since the problem was fixed elsewhere.  Thanks for the bug report and proposed fix!

**Pull request closed without merging**
